db:
  host: 'home.local'
  username: 'postgres'
  password: 'development'
  synchronize: true
  logging: true

jwt:
  secret: topSecret51

nats:
  url: nats://home.local:4222

verification:
  address: '192.168.1.33'

teamspeak:
  crawlInterval: 30
